name: test        # or whatever you like
channels:
  - defaults
dependencies:
  - python=3.8.8    
  - scipy=1.6.1
  - numpy=1.19.2
  - matplotlib=3.3.4
  - seaborn=0.11.1
  - pandas=1.2.3
  - tqdm=4.59.0
  - h5py=2.10.0
  - gmpy2=2.0.8
  - nltk=3.6.2
  - pillow=8.2.0
  - pip=21.0.1 
  - cudatoolkit=10.1.243
  - pip:
    - pysoundfile==0.9.0.post1
    - torch==1.8.1
    - torchvision==0.9.1
    - torchaudio==0.8.1
    - torchmetrics==0.3.2
    - pytorch-lightning==1.2.5
  - conda-forge::librosa=0.8.0